name: secrets-check
on:
  pull_request:

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chmod scripts
        run: chmod +x ./scripts/* || true
      - name: secrets-check
        run: ./scripts/secrets-check
