name: secrets-check
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * *"

permissions:
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chmod scripts
        run: chmod +x ./scripts/* || true
      - name: secrets-check
        run: ./scripts/secrets-check
